package org.options.platform.identity.api;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

/** Generated by scripts/generate-identity-dtos.py. */
public final class IdentityResponses {
  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record Session(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Boolean authenticated,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String accountId,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String state,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> roles,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String passwordAuthenticatedAt,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String webauthnAuthenticatedAt,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String idleExpiresAt,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String absoluteExpiresAt) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record Profile(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String accountId,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String email,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String displayName,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String theme,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String interestPathId,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Boolean verified,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String version) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record Credential(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String credentialId,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String label,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String createdAt,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Boolean backupEligible) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record Credentials(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<Credential> items) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record Acknowledgment(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String message) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record RegistrationOptionsRp(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String id,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String name) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record RegistrationOptionsUser(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String id,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String name,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String displayName) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record RegistrationOptionsPubKeyCredParamsItem(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String type,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Integer alg) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record RegistrationOptionsAuthenticatorSelection(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String residentKey,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String userVerification) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record RegistrationOptions(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String challenge,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) RegistrationOptionsRp rp,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) RegistrationOptionsUser user,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
          List<RegistrationOptionsPubKeyCredParamsItem> pubKeyCredParams,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Integer timeout,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
          List<CredentialDescriptor> excludeCredentials,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
          RegistrationOptionsAuthenticatorSelection authenticatorSelection,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String attestation) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record AssertionOptions(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String challenge,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) Integer timeout,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String rpId,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
          List<CredentialDescriptor> allowCredentials,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String userVerification) {}

  @Schema(additionalProperties = Schema.AdditionalPropertiesValue.FALSE)
  public record CredentialDescriptor(
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String type,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) String id,
      @Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> transports) {}
}
