#!/usr/bin/env python3
"""Deterministic P01 editorial interchange export, not an application model."""
from pathlib import Path
import json,re,hashlib
ROOT=Path(__file__).resolve().parents[1]
DATE='2026-09-22'; VERSION='1.0.0-design'
def read(p): return json.loads((ROOT/p).read_text())
def write(p,v):
 p=ROOT/p;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n' if not isinstance(v,str) else v)
def export(name,rows): write('data/v1/'+name+'.json',{'version':VERSION,'as_of':DATE,'records':rows})
def slug(s): return re.sub('[^a-z0-9]+','-',s.lower()).strip('-')
mi=read('research/inventory/modules.json'); ti=read('research/inventory/topics.json'); ri=read('research/inventory/resources.json');si=read('research/inventory/stages.json'); su=read('research/inventory/supplemental.json')
design={}
for line in (ROOT/'research/design/module-design.psv').read_text().splitlines():
 if line and not line.startswith('#'):
  a=line.split('|');assert len(a)==7,(a[0],len(a));design[a[0]]=a[1:]
assert len(design)==67
hard='''M01:;M02:M01;M03:M21;M04:M21;M05:M04;M06:M02;M07:M01;M08:M10;M09:M21,M10;M10:M01;M11:M10;M12:M11;M13:B02;M14:M13,M10;M15:M04,M11;M16:M15;M17:M15;M18:M15;M19:M15;M20:M04,M10;M21:B01;M22:M03;M23:M04,M22;M24:M22;M25:M24;M26:M25,M10;M27:M25,M32;M28:M29,M22;M29:M24,B02;M30:M29,M10;M31:M30,M13,B03;M32:M30;M33:M32,M13;M34:M32,M05;M35:M11;M36:M35,M30;M37:M36,M31;M38:M36,M22;M39:M36;M40:M37,M14;M41:M37,M34,M08;M42:M05;M43:M42,M30;M44:M31,M14;M45:M10,B01;M46:M45,M11;M47:M05,M22;M48:M46,M32;M49:M05,M22;M50:M04,M10;M51:M50,M34,M47;M52:M50,M05;M53:M25,M45,M52;M54:B03,M23;M55:M11,M54;M56:M55,M34,M47,M58;M57:M56,M13;M58:B03;M59:M53,M55;M60:B01,M10;M61:M11,M60;M62:M22,M47;M63:M22,M47;M64:M42,M47;M65:M11,M21;M66:M46,M49;M67:M56,M48,M49,M52,M61;B01:M01;B02:M01;B03:M01'''
pr={k:v.split(',') if v else [] for k,v in (x.split(':') for x in hard.split(';'))}
topological=[]
def prereq_visit(x):
 if x in topological:return
 for p in pr[x]:prereq_visit(p)
 topological.append(x)
for x in pr:prereq_visit(x)
bridges=[('B01','Loss, sizing and assignment intuition','Read obligations before imagining returns.','Can a small premium create a large delivery obligation?','Hypothetical short100put premium2 multiplier100: worst terminal loss9800 if stock reaches0, excluding costs.','Margin is maximum loss.','A','R01:II/VIII/X'),('B02','Algebra and slope bridge','Translate formulas, logs and local slopes into option units.','Why is a percentage-point shock different from a percentage shock?','20% volatility plus1 volatility point is21%, a5% relative increase.','Mixing decimal volatility and percent points.','A,C','R16:mathematical preparation; RX12:derivatives'),('B03','Python and reproducibility bridge','Write and rerun a small signed-cash-flow function before numerical projects.','Can another learner reproduce the environment and output?','Two contracts atpremium3 multiplier100 cost600 before fees; reject negative multiplier.','Unpinned dependencies and hidden notebook state.','A,N','R52:sections3–8; RX13:NumPy arrays')]
for id,title,why,q,num,err,math,reading in bridges:
 mi.append({'id':id,'title':title,'domain':'DB · Entry bridges','category':'Bridge','stage':0,'sources':[], 'prerequisites':[], 'advanced_extension':'Return to target competency after diagnostic','assessment':{'exercise':num,'mastery':'Explain units, complete a fresh variant and identify the critical error.'},'provenance':{'origin':'P01 design'}})
 design[id]=[why,q,num,err,math,reading]
 ti.append({'id':id+'.01','module_id':id,'title':title,'difficulty':'Beginner','importance':'Essential','evidence':'Curriculum-design recommendation','tags':'','subtopics':why+' '+num,'sources':[],'provenance':{'origin':'P01 design'}})
modules=[];comps=[];exercises=[];quizzes=[];assocs=[];topics=[];subtopics=[]
phase_names={'P0':'Entry and safety','P1':'Contracts and decision foundations','P2':'Pricing, mathematics and volatility','P3':'Research, risk and professional practice','P4':'Specialist branches'}
for m in mi:
 id=m['id'];why,q,num,err,math,reading=design[id];ts=[t for t in ti if t['module_id']==id];n=len(ts)
 specialist=id in ['M14','M27','M28','M33','M37','M38','M39','M40','M41','M43','M44','M51','M57','M64','M67']
 phase='P0' if id in ['M01','B01','B02','B03'] else 'P4' if specialist or id in ['M15','M16','M17','M18','M19','M20'] else 'P1' if id in ['M02','M03','M04','M05','M10','M21','M22','M23','M24','M25','M45','M60'] else 'P2' if id in ['M11','M12','M13','M26','M29','M30','M31','M32','M34','M35','M36'] else 'P3'
 hours=[2,5] if id.startswith('B') else [max(6,n),max(12,2*n+8)]
 if specialist: hours=[max(15,2*n),max(25,3*n+12)]
 prereqs={'hard':['C-'+x for x in pr[id]],'recommended':['C-'+x for x in m['prerequisites'] if x not in pr[id] and topological.index(x)<topological.index(id)],'optional':[]}
 if id=='M14':prereqs['optional']=['C-M40'] # enrichment is not an entry requirement; may be a later revisit
 cid='C-'+id
 comp={'id':cid,'module_id':id,'outcome':why,'hard_prerequisites':prereqs['hard'],'recommended_preparation':prereqs['recommended'],'optional_enrichment':prereqs['optional'],'dependency_reason':'The predecessor supplies the named numerical, contract, data or risk skill consumed in this module; diagnostic evidence may satisfy it without repeating a whole module.','assessment_ids':['EX-'+id+'-N','EX-'+id+'-P'],'diagnostic':{'prompt':q,'bridge':('B03' if id in ['M31','M54','M55','M56','M57','M58'] else 'B02' if any(x in math.split(',') for x in ['C','I','L']) else 'B01'),'pass':'Explain assumptions and units; solve a fresh entry task without a critical cash, assignment or loss-bound error. Diagnostic placement is provisional, checked by the module assessment.'}}
 comps.append(comp)
 objective=[why,'Solve and explain: '+num,'Audit the failure mode: '+err]
 mod={'id':id,'slug':slug(m['title']),'title':m['title'],'program_id':'OPT','phase_id':phase,'domain_id':m['domain'].split(' · ')[0],'level':'Advanced' if specialist else ('Beginner' if phase in ['P0','P1'] else 'Intermediate'),'tags':[slug(m['category']),slug(m['domain'].split(' · ')[-1])],'prerequisites':prereqs,'study_hours':hours,'estimate_basis':'Editorial estimate for selected readings, scope navigation, one worked calculation, one transfer variant, practical work and remediation; 45–90 minutes per ordinary scope topic plus 2–8 practical hours, longer for specialist derivation. Projects budgeted separately. Not measured learner time.','why_it_matters':why,'objectives':objective,'competency_ids':[cid],'topic_ids':[t['id'] for t in ts],'required_math':math.split(','),'required_programming':'B03 plus arrays, functions and tests' if id in ['M31','M37','M40','M54','M55','M56','M57','M58','M67'] else 'None for core explanations; optional Python for replication','reading_assignments':reading,'exercise_ids':['EX-'+id+'-C','EX-'+id+'-N','EX-'+id+'-P'],'quiz_id':'QZ-'+id,'practical_assignment':m['assessment']['exercise'],'common_mistakes':[err,'Accepting a result without its units, assumptions or source date.'],'checkpoint_questions':[q,'Which assumption in your numerical result is most vulnerable, and what changes if it fails?'],'mastery_criteria':[m['assessment']['mastery'],'At least 85% on quiz and rubric; no unresolved critical errors; solve a fresh transfer variant with reasoning.'],'remediation':'Diagnose the mistaken unit, model, observation or cash-flow step; revisit the cited entry bridge or source section, annotate the correction, then attempt an unseen variant after a separate review session.','readiness':'learning_design','lesson_authoring_owner':'P17','original_provenance':m['provenance']}
 modules.append(mod)
 for typ,prompt,answer in [('C',q,'Use the module objective and stated failure mode; credit explicit conditions and a counterexample, not confidence.'),('N','Compute, show units and assumptions; then change one input and justify the direction. '+num,num),('P',m['assessment']['exercise'],m['assessment']['mastery'])]:
  exercises.append({'id':'EX-'+id+'-'+typ,'module_id':id,'competency_ids':[cid],'type':{'C':'conceptual','N':'numerical','P':'practical'}[typ],'prompt':prompt,'reference_behavior':answer,'data':'Original hypothetical numbers; no market dataset required for N. P may use synthetic or lawfully licensed data with provenance.','deliverable':'Worked reasoning and cash/unit ledger; for practical work include assumptions, failure case and reproducibility notes.','rubric':{'correctness':35,'units_and_assumptions':25,'failure_analysis':25,'communication':15},'pass_score':85,'critical_errors':['contract_units','cash_obligation','assignment','leverage','loss_bound'],'tolerance':'N: exact arithmetic where integer; displayed numerical values within last quoted digit or stated rounding; P: assessor checks rubric, not a profit threshold.','fresh_variant':'Change the strike/multiplier, sampling window or stress assumption as applicable; withhold the reference until the learner submits.','status':'authored_prompt_reference; transfer variants require P17 authoring','noncoding_route':'Paper or accessible spreadsheet for arithmetic; written audit of supplied pseudocode for implementation reasoning. Coding-dependent competencies still require executable code.'})
 quizzes.append({'id':'QZ-'+id,'module_id':id,'competency_ids':[cid],'items':[{'kind':'explain','question':q,'weight':25},{'kind':'calculate','exercise_id':'EX-'+id+'-N','weight':35},{'kind':'failure_case','question':'Diagnose and repair: '+err,'weight':25},{'kind':'transfer','question':'Change an assumption in the practical assignment; explain the decision consequence.','weight':15}],'pass_score':85,'critical_error_policy':'Any unresolved critical error blocks mastery regardless of total.','retries':'Fresh variant after documented remediation; retain attempts and rubric version.','status':'blueprint; not a calibrated item bank'})
 for rid in dict.fromkeys(re.findall(r'\bR(?:X\d+|\d+)\b',reading)):
  # Module proposals are not source-section verification. Exact reviewed
  # assignments are added separately with bounded claim references.
  clauses=list(re.finditer(r'(R(?:X)?\d{2}(?:/R(?:X)?\d{2})*):',reading))
  scopes=[reading[c.end():clauses[j+1].start() if j+1<len(clauses) else len(reading)].strip('; ') for j,c in enumerate(clauses) if rid in c.group(1).split('/')]
  assert len(scopes)==1,(id,rid,reading)
  assocs.append({'id':'A-'+id+'-'+rid,'resource_id':rid,'competency_id':cid,'topic_ids':[],'reading_scope':scopes[0],'purpose':'Module reading proposal; verify the named section before required use. Not evidence for every topic in the module.','status':'assignment_candidate','evidence_claim_ids':[]})
for t in ti:
 mid=t['module_id']; scope=t['subtopics'];sid=t['id']+'.S01'
 topics.append({'id':t['id'],'module_id':mid,'title':t['title'],'difficulty':t['difficulty'],'priority':t['importance'],'evidence_class_original':t['evidence'],'classification_code_original':t['tags'],'tags':[slug(next(m['category'] for m in mi if m['id']==mid))],'subtopic_ids':[sid],'scope_outline':scope,'teaching_brief':None,'teaching_brief_unknown_reason':'P17 must author a topic-specific explanation, worked example and transfer task; module-level design is available but is not a finished topic brief.','reviewed_lesson':None,'readiness':'scope_outline','original_provenance':t['provenance']})
 # Keep each coherent original scope as one addressable unit; never split punctuation as if it carried semantics.
 subtopics.append({'id':sid,'topic_id':t['id'],'title':t['title']+' — scope unit','scope':scope,'competency_ids':['C-'+mid],'readiness':'scope_outline','granularity_note':'One preserved semantic scope unit, addressable independently. Author may split into narrower reviewed units with successor mappings in P17; no comma-based atomization.'})
# Explicit additions discovered through research, not claimed as authored lessons.
for id,mid,title,scope in [('M37.P01','M37','American-quote treatment','Identify exercise premium and discrete dividends; compare direct American-model calibration with de-Americanization; bound error, preserve bid/ask and exercise-model uncertainty.'),('M63.P01','M63','Closing-auction rule transition','Reconstruct the 2026 CAS circular chain, instrument scope, close and hedge timestamps; reject hard-coded legacy closing times.'),('M66.P01','M66','Regulator report consistency audit','Reconcile R56 Table 5 against prose units and denominators; quarantine buyer/seller headline averages until corrected or raw data verified.')]:
 topics.append({'id':id,'module_id':mid,'title':title,'difficulty':'Advanced','priority':'Essential','evidence_class_original':'P01 research finding','classification_code_original':None,'tags':['source-validation'],'subtopic_ids':[id+'.S01'],'scope_outline':scope,'teaching_brief':scope+' Assessment: reproduce the discrepancy or model comparison and state what cannot be inferred.','teaching_brief_unknown_reason':None,'reviewed_lesson':None,'readiness':'teaching_brief','original_provenance':{'origin':'P01 research'}})
 subtopics.append({'id':id+'.S01','topic_id':id,'title':title,'scope':scope,'competency_ids':['C-'+mid],'readiness':'teaching_brief','granularity_note':'New bounded semantic unit.'})
 next(m for m in modules if m['id']==mid)['topic_ids'].append(id)
export('modules',modules);export('competencies',comps);export('topics',topics);export('subtopics',subtopics);export('exercises',exercises);export('quiz_blueprints',quizzes)
export('programs',[{'id':'OPT','title':'Options: contracts, volatility, research and professional practice','phase_ids':list(phase_names),'qualification':'Educational curriculum design; no accreditation or promise of trading profitability.'}]);export('phases',[{'id':k,'title':v,'module_ids':[m['id'] for m in modules if m['phase_id']==k]} for k,v in phase_names.items()])
# Keep the originals verbatim in archival records; source mappings below distinguish preserved representations.
export('archival_structures',[{'id':'SUP-'+k,'kind':k,**v} for k,v in su.items()]+[{'id':'OLD-STAGE-'+str(s['stage']),'kind':'stage','original':s,'disposition':'Retained as original navigation; replaced by competency paths for entry order.'} for s in si])
# Resources: unknown is a value plus an explanation, never fabricated metadata.
paid={'R05','R06','R07','R08','R10','R11','R24','R27','R28','R39','R44','R50','R66','R70','R71','R72'}
verified={'R01':'June2024 ODD contents and selected II/VIII/X excerpts; not all96 PDF pages','R04':'Options education body','R05':'Publisher11th-edition TOC and ISBN only; no full book','R06':'Publisher2nd-edition metadata only; no full book','R09':'SPAN2 overview formula and scope; not implementation manual','R10':'Publisher2nd-edition2013 metadata only; no full book','R12':'Author PDF summary, pp9–18 replication; other assigned sections await review','R18':'Real-time vintage documentation','R23':'Full PDF retrieved; sections1–3 selected for critical reading, numerical replication not performed','R29':'NBER abstract/method description only; empirical generalization excluded','R32':'Exchange article retrieved; precise sample claims remain unverified','R34':'Original Nobel lecture retrieved; ARCH motivation selected, no empirical replication','R35':'PDF sections2–3 read; sections4–5 assignment pending close review','R36':'FAQ calculation/product distinctions read; exact current methodology chain incomplete','R45':'SR26-2 letter including supersession; attachment not fully reviewed','R52':'Tutorial directory and selected language topics; learner environment not built in P01','R55':'User-guide directory only','R56':'PDF pp5–6,10–19,51–53; p14/18 visually checked. Numeric conflict quarantined','R57':'Directory/specifications and FAOP68747/70616 operative notices; no daily master reconciliation','R58':'Table and computation basis read; primary statute chain incomplete; internal wording conflict flagged','R60':'File format document only, not contract specifications','R61':'Rule4210(g) excerpts only; amendments not exhaustively traced','R67':'Official1999 testimony retrieved; case reading scope','R68':'SEC2021 report pp24–34 selected; gamma-squeeze paragraph read','R73':'Official publication landing metadata; full paper not reviewed'}
resource_rows=[]
access=read('research/evidence/resource-access-p01.json')
accessrows=access.get('records',access.get('results',[])) if isinstance(access,dict) else access
# Access report layout remains separately authoritative even if no row is matched here.
for r in ri:
 rid=r['id'];author=r['title'].split(' — ')[0];status='selected_sections_reviewed' if rid in verified and not any(x in verified[rid] for x in ['only','remain unverified','not reviewed','pending']) else 'limited_review' if rid in verified else 'access_or_inherited_metadata_only'
 resource_rows.append({'id':rid,'title':r['title'],'author_organization':author,'canonical_url':r['url'],'doi':None,'edition':None,'resource_type':r['kind'],'difficulty':r['level'],'cost':'paid' if rid in paid else 'mixed' if rid in ['R02','R03','R51'] else 'free','access_limitations':r['access']+' P01: '+verified.get(rid,'Transport checked; original descriptive claims not independently verified in full.'),'study_hours':[1,4] if rid not in paid else [3,8],'time_basis':'Selected assignment estimate including notes/exercise; not whole-book duration. Refine after learner pilots.','topics_competencies':['C-'+x for x in r['used_in_modules']],'recommended_audience':'See explicitly assigned competencies; level is inherited and subject to placement diagnostics.','rationale':r['why'],'prerequisites':'Module competency prerequisites; advanced books are reference selections, not beginner entry requirements.','priority':'Essential' if rid in ['R01','R04','R52'] else 'Reference' if rid in paid else 'Recommended','role':'foundational' if rid in ['R01','R04','R21','R52'] else 'optional','geography':'India' if rid in ['R56','R57','R58','R59','R60'] else 'Global concepts; source jurisdiction must be checked for rules','publication_date':None,'updated_date':None,'last_verification_date':DATE,'verification_scope':verified.get(rid,'Transport/access attempt only; see research/evidence/resource-access-p01.json. No full-content review claimed.'),'rights':'Link and original commentary only. No third-party full text or market data redistributed; permission not inferred from free access.','status':status,'replacement_ids':[],'supersedes_ids':[],'unknowns':{'doi':'Not independently established for every item in P01','edition':'Not applicable or edition not established; see verified book overrides','publication_date':'Not established from reviewed source unless override','updated_date':'No reliable update date established'},'original_provenance':r['provenance']})
extras=[
('RX01','Exercising Options','OIC','https://www.optionseducation.org/optionsoverview/exercising-options','official education','Beginner','full article: instructions, assignment, early exercise and expiry uncertainty','M03 M21 M22 M53','free'),
('RX02','Put-Call Parity','OIC','https://www.optionseducation.org/advancedconcepts/put-call-parity','official education','Intermediate','body assumptions, synthetic positions and no-friction example; carry extension must be derived explicitly','M24 M28 M29','free'),
('RX03','Black-Scholes Formula','OIC','https://www.optionseducation.org/advancedconcepts/black-scholes-formula','official education','Intermediate','article assumptions and variable definitions; not a numerical library specification','M30 M32','free'),
('RX04','De-Americanization of Option Prices: Effect on Calibration','Burkovska, Gaß, Glau, Mahlstedt and Schoutens','https://arxiv.org/abs/1611.06181','primary preprint','Advanced','2016 arXiv preprint; conclusion and benchmark scope read, sections3–4 assigned; dividends excluded from reported study scope','M37 M40','free'),
('RX05','Dynamic Hedging: Managing Vanilla and Exotic Options','Nassim Nicholas Taleb','https://www.wiley-vch.de/en/areas-interest/finance-economics-law/dynamic-hedging-978-0-471-15280-4','book','Advanced','Publisher metadata and contents only; first edition1997 ISBN9780471152804; not full review','M33 M34 M44 M51','paid'),
('RX06','Paul Wilmott Introduces Quantitative Finance, 2nd Edition','Paul Wilmott','https://uat.store.wiley.com/en-us/paul-wilmott-introduces-quantitative-finance-2nd-edition-p-9780470319581','book','Advanced','Publisher metadata2007 ISBN9780470319581; selected PDE/numerics chapters require lawful copy and page verification','M13 M14 M30 M31','paid'),
('RX07','Options as a Strategic Investment, 5th Edition','Lawrence G. McMillan','https://www.penguinrandomhouse.com/books/310812/options-as-a-strategic-investment-by-lawrence-g-mcmillan/','book','Intermediate','Publisher2012 metadata ISBN9780735204652; broad strategy reference, not current tax authority; full text not reviewed','M24 M25 M26 M27','paid'),
('RX08','The Complete Guide to Option Pricing Formulas, 2nd Edition','Espen Gaarder Haug','https://www.mheducation.com/highered/mhp/product/complete-guide-to-option-pricing-formulas-2e.html','book','Advanced','Publisher TOC and ISBN9780071389976; published2006 copyright2007; chapters2/3/4/5/7/8 assignment candidates, no full review','M31 M33 M44','paid'),
('RX09','Trading Volatility for Profit: Using VIX as a Predictive Indicator to Find Winning Trades','Lawrence G. McMillan','https://uat.store.wiley.com/en-us/trading-volatility-for-profit-using-vix-as-a-predictive-indicator-to-find-winning-trades-p-9781118633564','video','Intermediate','Publisher metadata:90-minute2013 video ISBN9781118633564; not watched, timestamps unknown; predictive marketing not adopted','M39','paid'),
('RX10','Trading Volatility: Trading Volatility, Correlation, Term Structure and Skew','Colin Bennett','https://www.trading-volatility.com/downloads.html','practitioner book','Advanced','Author-hosted2014 book ISBN9781499206074 located; selected contents/sections recorded in evidence supplement; free access not redistribution','M35 M36 M37 M41','free'),
('RX11','VIX White Paper','Cboe','https://cdn.cboe.com/resources/futures/vixwhite.pdf','index methodology','Advanced','Retrieval attempted; current version/addendum chain not certified. Do not substitute VIXMO or single-stock volatility methodology.','M39','free'),
('RX12','18.01SC Single Variable Calculus, Fall2010','MIT OCW','https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/','university course','Beginner','Course outline; Unit1 derivatives and Unit2 integration assignment candidates; exact video timestamps not reviewed','M13','free'),
('RX13','NumPy: the absolute basics for beginners','NumPy contributors','https://numpy.org/doc/stable/user/absolute_beginners.html','software documentation','Beginner','Arrays, shape, indexing and broadcasting page reviewed by section; stable URL moves with releases','M58','free'),
('RX14','scipy.optimize.brentq','SciPy contributors','https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brentq.html','software documentation','Intermediate','Specific solver documentation requires endpoint sign bracket and tolerance check; selected as IV-solver reading','M31','free'),
('RX15','Common pitfalls and recommended practices','scikit-learn contributors','https://scikit-learn.org/stable/common_pitfalls.html','software documentation','Intermediate','12.1–12.2 train/test preprocessing leakage read; temporal split design remains separately necessary','M57','free'),
('RX16','A Brief History of the1987Stock Market Crash with a Discussion of the Federal Reserve Response','Mark Carlson / Federal Reserve','https://www.federalreserve.gov/pubs/feds/2007/200713/index.html','central-bank working paper','Intermediate','FEDS2007-13; chronology and competing portfolio-insurance interpretations, not definitive causal identification','M66','free'),
('RX17','The equity market turbulence of5February—the role of exchange-traded volatility products','BIS','https://www.bis.org/publications/equity-market-turbulence-5-february-role-exchange-traded-volatility-products','institutional research','Intermediate','March2018 pp4–6 and corrected graph note; leveraged/inverse product rebalancing mechanism','M39 M66','free'),
('RX18','Holistic Review of the March Market Turmoil','Financial Stability Board','https://www.fsb.org/2020/11/holistic-review-of-the-march-market-turmoil/','official report','Advanced','2020-11-17; overview and margin/liquidity sections selected; no universal cause inferred','M46 M47 M66','free'),
('RX19','yfinance','Ran Aroussi and contributors','https://github.com/ranaroussi/yfinance','software project','Intermediate','README/legal and license identification reviewed; Apache2.0 software, separate Yahoo data terms; no production feed assurance','M54 M58','free'),
('RX20','VIX Index End-of-Day Calculation Inputs','Cboe DataShop','https://datashop.cboe.com/vix-index-eod-calculation-inputs','market dataset','Advanced','Product licensing description: redistribution/additional use may require separate licensing; no dataset purchased','M39 M54','paid'),
('RX21','statsmodels User Guide','statsmodels contributors','https://www.statsmodels.org/stable/user-guide.html','software documentation','Intermediate','Directory located; exact estimation diagnostics assigned by model, API/version validation pending','M12 M58','free'),
('RX22','Matplotlib tutorials','Matplotlib contributors','https://matplotlib.org/stable/tutorials/index.html','software documentation','Beginner','Directory; explicit labels, units and textual equivalents required; example execution pending','M58','free')]
for id,title,author,url,kind,level,scope,mids,cost in extras:
 resource_rows.append({'id':id,'title':title,'author_organization':author,'canonical_url':url,'doi':None,'edition':None,'resource_type':kind,'difficulty':level,'cost':cost,'access_limitations':scope,'study_hours':[1,3] if kind not in ['book','practitioner book'] else [3,8],'time_basis':'Editorial estimate for selected sections and one exercise; no whole-book assignment.','topics_competencies':['C-'+x for x in mids.split()],'recommended_audience':level+' learners in assigned modules','rationale':scope,'prerequisites':'Hard prerequisites of assigned competencies.','priority':'Optional' if id=='RX09' else 'Advanced' if level=='Advanced' else 'Recommended','role':'optional','geography':'Global conceptual; US product rules only where stated','publication_date':None,'updated_date':None,'last_verification_date':DATE,'verification_scope':scope,'rights':'Link only. Software license and data entitlement are separate; no third-party text or data included.','status':'limited_review','replacement_ids':[],'supersedes_ids':[],'unknowns':{'doi':'Not verified or not applicable','edition':'See textual scope; not machine-certified','publication_date':'See bibliographic notes when verified; otherwise unknown','updated_date':'Moving source, no pinned revision reviewed'},'original_provenance':{'origin':'P01 research'}})
for rid,edition,pub in [('R05','11; ISBN9780136939979',None),('R06','2; ISBN9780071818773','2014-10-31'),('R10','2; DOI10.1002/9781118662724','2013'),('RX05','1; ISBN9780471152804','1997-01'),('RX06','2; ISBN9780470319581','2007-08'),('RX07','5; ISBN9780735204652','2012-08-07'),('RX08','2; ISBN9780071389976','2006-12-18'),('RX10','ISBN9781499206074','2014')]:
 r=next(x for x in resource_rows if x['id']==rid);r.update(edition=edition,publication_date=pub);r['unknowns'].pop('edition');
 if pub:r['unknowns'].pop('publication_date')
# Free source alternatives support concepts, never imply equivalent full advanced-book coverage.
for r in resource_rows:
 r['free_alternative_ids']=['RX01','RX02','RX03','R21','R35'] if r['cost']=='paid' and r['id']!='RX20' else []
 r['alternative_limit']='Choose the assigned competency-specific alternative; this list is a conceptual route, not chapter-for-chapter equivalence.'
export('resources',resource_rows)
known={x['id'] for x in resource_rows};assert all(x['resource_id'] in known for x in assocs),[x for x in assocs if x['resource_id'] not in known]
export('associations',assocs)
# Paths derive the prerequisite closure deterministically, preserving target order and explicit branches.
path_specs=[('PATH-BEGINNER','Absolute Beginner',['M01','B01','M21','M03','M22','M04','M05','M24','M10','M45','M60'],'No prior finance; basic reading and arithmetic, B01 includes safety bridge.','Explain contract obligations, compute net payoff and size a synthetic position.',['M25','M62','M63']),('PATH-RETAIL','Retail Options Trader',['M25','M32','M34','M35','M36','M38','M45','M47','M49','M52','M53','M61','M65'],'Beginner exit or equivalent diagnostic.','Write a falsifiable costed strategy dossier and manage a simulated lifecycle.',['M15','M27','M62','M63']),('PATH-QUANT','Quantitative Options Trader',['B03','M58','M13','M14','M31','M33','M37','M40','M54','M55','M56','M46'],'Algebra and probability diagnostic; bridge calculus and Python as needed.','Validate pricing/calibration and an out-of-sample research experiment.',['M43','M44','M57']),('PATH-VOL','Volatility Trader',['M34','M35','M36','M37','M38','M39','M41','M47','M52','M55','M56'],'Contract, Greek and inference diagnostics.','Separate variance premium, forecast, hedge error and execution costs.',['M40','M44','M51']),('PATH-MM','Market-Making',['M50','M51','M33','M37','M47','M49','M52','M54','M56','M67'],'Pricing, probability and executable-code diagnostics.','Run a simulated inventory/quoting desk with adverse-selection and recovery controls.',['M40','M43','M44']),('PATH-INDIA','Indian Options Trader',['M25','M45','M47','M49','M63','M32','M34','M52','M53','M61','M65'],'Beginner exit or bridge; no current contract facts assumed.','Reconcile dated index/stock obligations and costs using circular and contract evidence.',['M38','M39','M64']),('PATH-SYSTEMATIC','Systematic Options Trader',['B03','M58','M54','M55','M56','M48','M49','M59','M61','M67'],'Probability, contract and Python diagnostics.','Reproduce a research-to-simulation pipeline with capital and operational constraints.',['M12','M57','M41'])]
paths=[]
for id,title,targets,entry,exitc,branches in path_specs:
 order=[]
 def visit(x):
  if x in order:return
  for p in pr[x]:visit(p)
  order.append(x)
 for t in targets:visit(t)
 hs=[sum(next(m for m in modules if m['id']==x)['study_hours'][j] for x in order) for j in range(2)]
 paths.append({'id':id,'title':title,'audience':title,'entry_criteria':entry,'diagnostic_ids':['C-'+x for x in targets[:2]],'module_sequence':order,'target_modules':targets,'branches':[{'module_id':x,'rule':'Complete its hard competency prerequisites before entry; optional depth.'} for x in branches],'exit_competencies':[exitc],'exit_competency_ids':['C-'+x for x in targets],'study_hours':hs,'estimate_basis':'Sum unique module selected-study ranges; diagnostic credit reduces repeats; project hours additional. No fixed time-to-profit promise.','assessment_gates':['QZ-'+x for x in order],'milestone_gates':['No critical contract/cash/assignment error before structures.','No coding-dependent project before B03; no backtest before M54/M55.','Final rubric85% and reproducible transfer task; real money never required.']})
export('learning_paths',paths)
# An exhaustive archival map for all original entities and relationships; raw sources immutable.
maprows=[]
def mapped(id,kind,loc,target,disposition='retained',note='Original text preserved; canonical scope/design is not a reviewed lesson.'):
 maprows.append({'id':'MAP-'+id,'original_id':id,'kind':kind,'provenance':loc,'canonical_ids':target,'disposition':disposition,'note':note})
for m in mi[:67]:mapped(m['id'],'module',m['provenance'],[m['id']])
for t in ti[:1019]:
 mapped(t['id'],'topic',t['provenance'],[t['id']]);mapped(t['id']+'-scope','subtopic_scope',t['provenance'],[t['id']+'.S01'])
for r in ri:mapped(r['id'],'resource',r['provenance'],[r['id']])
for s in si:mapped('STAGE-'+str(s['stage']),'sequence',{'source':'sources/roadmaps/options-curriculum-catalog.json','json_pointer':'/stages/'+str(s['stage'])},['OLD-STAGE-'+str(s['stage'])],'archived_navigation','Original sequence preserved; competency paths permit earlier contracts, risk and coding.')
for m in mi[:67]:
 mapped(m['id']+'-assessment','exercise_checkpoint',m['provenance'],['EX-'+m['id']+'-P','QZ-'+m['id']]);
 for p in m['prerequisites']:mapped(m['id']+'-prereq-'+p,'prerequisite',m['provenance'],['C-'+m['id'],'C-'+p],'reclassified','Original edge preserved here; canonical hard/recommended separation controls entry.')
 for rid in m['sources']:mapped(m['id']+'-resource-'+rid,'module_resource',m['provenance'],[m['id'],rid],'archived_context','Original broad association is not an exact citation.')
for t in ti[:1019]:
 for rid in t['sources']:mapped(t['id']+'-resource-'+rid,'inherited_topic_resource',t['provenance'],[t['id'],rid],'archived_context','Inherited link preserved but not promoted to a claim-level citation.')
for k,v in su.items():mapped('SUP-'+k,'supplemental',{'source':v['source'],'line':v['line']},['SUP-'+k])
for d in sorted({m['domain'] for m in mi[:67]}):mapped(d.split(' · ')[0],'domain',{'source':'research/inventory/modules.json','selector':d},[d.split(' · ')[0]])
export('source_mappings',maprows)
# Source-by-source ratings: grade what exists, not whether a name appears.
coverage=[]
for row in maprows:
 kind=row['kind'];rating='Good' if kind in ['module','domain','sequence','supplemental'] else 'Partial' if kind in ['topic','subtopic_scope','exercise_checkpoint'] else 'Weak' if kind in ['resource','inherited_topic_resource','module_resource'] else 'Good'
 coverage.append({'id':'COV-'+row['original_id'],'mapping_id':row['id'],'kind':kind,'rating':rating,'evidence':row['provenance'],'scope':'present','accuracy':'not blanket-certified; see claim register','teaching':'scope-only' if kind in ['topic','subtopic_scope'] else 'module design/archival context','practice':'module prompt/reference exists; full item bank remains P17','verification':'exact archival parity; external claims only where evidence register supports them','maintenance':'dated rules and review queue; no permanent contract constants','disposition':row['disposition']})
write('research/registers/coverage-matrix.json',{'rating_definitions':{'Excellent':'Accurate bounded instruction, worked practice, transfer assessment and current evidence all reviewed; no original item receives this merely for breadth.','Good':'Coherent scope or structure with usable design; specified teaching/evidence work remains.','Partial':'Concept present but explanation or practice incomplete.','Weak':'Mention, inherited citation or unverified annotation provides little direct teaching/evidence.','Missing':'No original item; new omission recorded in gap/checklist register.'},'records':coverage})
# Generated navigable human module dossiers, with distinct authored calculations.
for m in modules:
 c=next(c for c in comps if c['id']=='C-'+m['id']);es=[e for e in exercises if e['module_id']==m['id']]
 text=f"# {m['id']} — {m['title']}\n\nStatus: learning design; topic lessons remain P17. Slug: `{m['slug']}`. {m['level']}; {m['study_hours'][0]}–{m['study_hours'][1]} hours. Tags: {', '.join(m['tags'])}.\n\n{m['why_it_matters']}\n\nHard prerequisites: {', '.join(m['prerequisites']['hard']) or 'none'}. Recommended preparation: {', '.join(m['prerequisites']['recommended']) or 'none'}. Optional enrichment: {', '.join(m['prerequisites']['optional']) or 'none'}. Diagnostic: {c['diagnostic']['prompt']} Bridge: {c['diagnostic']['bridge']}.\n\nEstimation basis: {m['estimate_basis']}\n\nObjectives:\n\n"+'\n'.join('- '+x for x in m['objectives'])+f"\n\nMathematics: {', '.join(m['required_math'])} (codes in MATH_ROADMAP). Programming: {m['required_programming']}.\n\nReading: {m['reading_assignments']}. Resource verification limits control use; a TOC assignment is a candidate, not a reviewed chapter. All learners can complete the synthetic numerical case without buying a book.\n\nOrdered scope:\n\n"+'\n'.join('- '+t['id']+' — '+t['title']+': '+t['scope_outline'] for t in topics if t['module_id']==m['id'])+'\n\nTeaching brief for module delivery: begin with the checkpoint dilemma, elicit the learner\'s units and obligations, work the numerical case, then use the practical assignment to challenge the main assumption. Ask for a counterexample before extending the scope. This is a module delivery plan, not a topic lesson.\n\nPractice:\n\n'+'\n\n'.join('**'+e['id']+'** '+e['prompt']+'\n\nReference: '+e['reference_behavior'] for e in es)+'\n\nCommon mistakes:\n\n'+'\n'.join('- '+x for x in m['common_mistakes'])+'\n\nCheckpoint questions:\n\n'+'\n'.join('- '+x for x in m['checkpoint_questions'])+'\n\nMastery:\n\n'+'\n'.join('- '+x for x in m['mastery_criteria'])+'\n\nRemediation: '+m['remediation']+'\n'
 write('docs/curriculum/modules/'+m['id']+'.md',text)
write('data/v1/manifest.json',{'version':VERSION,'as_of':DATE,'purpose':'P01 curriculum interchange and research design; not application persistence schema','source_hashes':read('research/inventory/summary.json')['source_manifest'],'counts':{'modules':len(modules),'topics':len(topics),'subtopics':len(subtopics),'resources':len(resource_rows),'competencies':len(comps),'exercises':len(exercises),'quiz_blueprints':len(quizzes),'source_mappings':len(maprows)},'publication_ready_lessons':0})
print(json.dumps({'built':VERSION,'modules':len(modules),'topics':len(topics),'mappings':len(maprows)}))
