#!/usr/bin/env python3
from pathlib import Path
import json,re
R=Path(__file__).resolve().parents[1];DATE='2026-09-22';V='1.0.0-design'
def read(p):return json.loads((R/p).read_text())
def out(name,rows,base='data/v1'):(R/base/(name+'.json')).write_text(json.dumps({'version':V,'as_of':DATE,'records':rows},ensure_ascii=False,indent=2)+'\n')
ps=[]
for l in (R/'research/design/projects.psv').read_text().splitlines():
 if not l or l.startswith('#'):continue
 a=l.split('|');assert len(a)==10,a[0]
 id,title,req,obj,steps,deliver,reference,fail,limit,hours=a
 ps.append({'id':id,'title':title,'prerequisites':req.split(),'learning_objective':obj,'data_plan':'Default: generated hypothetical/synthetic data with seed, parameter manifest and no third-party market observations. Optional real data requires written entitlement, retention/export terms and timestamped lineage.','steps':steps.split(';'),'deliverables':deliver,'reference_behavior':reference,'rubric':{'cash_and_numerical_correctness':30,'assumptions_and_data_lineage':20,'validation_and_failure_cases':25,'decision_and_limitations':15,'reproducibility_accessibility':10},'pass_score':85,'critical_failure':'Units, cash, assignment, leaked evaluation or false entitlement claim blocks mastery regardless of score.','failure_cases':fail.split(';'),'limitations':limit,'study_hours':[int(x) for x in hours.split(',')],'estimate_basis':'Design estimate for implementation, audit and one revision; prior competencies assumed.','status':'project_specification','real_money_required':False,'noncoding_route':'PR01 foundational cash tables available without code; audit supplied ledgers for other projects, but this does not award executable-code competency.'})
out('projects',ps)
su=read('research/inventory/supplemental.json');caps=[];cards=[];branches=[]
links=[['PR01'],['PR02','PR03','PR05','PR07'],['PR04','PR06','PR09','PR10'],['PR01','PR08'],['PR07','PR11'],['PR08','PR09','PR10','PR11','PR12'],['PR08','PR12']]
for i,l in enumerate(su['capstones']['markdown'].splitlines()):
 m=re.match(r'(\d+)\. \*\*(.*?):\*\* (.*)',l)
 if m:
  n=int(m[1]);caps.append({'id':f'C{n:02d}','title':m[2],'original_brief':m[3],'project_ids':links[n-1],'assessment_policy':'POL-01','source':su['capstones']['source'],'line':su['capstones']['line']+i,'status':'preserved_and_integrated'})
for i,l in enumerate(su['decision_card']['markdown'].splitlines()):
 m=re.match(r'(\d+)\. (.*)',l)
 if m:cards.append({'id':'DC'+m[1].zfill(2),'question':m[2],'source':su['decision_card']['source'],'line':su['decision_card']['line']+i,'required_in_capstones':['C04','C06','C07']})
for i,l in enumerate(su['specialization_branches']['markdown'].splitlines()):
 if l.startswith('|') and not l.startswith('| Track') and not l.startswith('|---'):
  cells=[x.strip() for x in l.strip('|').split('|')]
  if len(cells)==3:branches.append({'id':f'BR{len(branches)+1:02d}','title':cells[0],'original_module_scope':cells[1],'depth':cells[2],'source':su['specialization_branches']['source'],'line':su['specialization_branches']['line']+i,'status':'preserved_specialization; resolve prerequisites through competency graph'})
assert len(caps)==7 and len(cards)==23 and len(branches)==7,(len(caps),len(cards),len(branches))
out('capstones',caps);out('decision_cards',cards);out('specializations',branches)
out('assessment_policies',[{'id':'POL-01','version':1,'threshold':85,'critical_errors':['contract_units','cash_obligation','assignment','leverage','loss_bound','data_leakage','unlawful_data_use'],'states':['viewed','self_completed','attempted','demonstrated_mastery'],'evidence':'Versioned response, rubric, assessor identity/role, source snapshot, score, critical errors and fresh transfer task. P01 defines fields, not an application learner model.','retry':'Preserve earlier attempt; targeted remediation; unseen variant. No completion by attendance or investment returns.','calibration':'85% is an inherited pedagogical default, not psychometrically validated certification. P17 pilots must evaluate item reliability and accessibility.'}])
# Dated rules: verified historical provisions are distinct from a certified current contract master.
rules=[]
def rule(id,instrument,juris,typ,value,unit,url,circ,pub,eff,status,scope,unc,prior=None,to=None):
 rules.append({'id':id,'instrument':instrument,'jurisdiction':juris,'rule_type':typ,'value':value,'unit':unit,'source_url':url,'circular_identifier':circ,'publication_date':pub,'effective_from':eff,'effective_to':to,'verification_date':DATE,'supersedes':prior or [],'superseded_by':[],'review_status':status,'scope':scope,'uncertainty':unc,'review_owner':'curriculum rules editor','review_interval_days':7 if juris=='India' else 30,'publication_eligible':status=='historical_verified','unknown_date_reason':'Null end date means not established, not proof of perpetual validity.'})
rule('RULE-IN-01','NSE individual-stock derivatives','India','settlement','physical','delivery','https://www.sebi.gov.in/sebi_data/attachdocs/dec-2018/1546255335099.pdf','SEBI/HO/MRD/DOPI/CIR/P/2018/161','2018-12-31','2019-04-01','historical_verified','Staged mandate: bottom50 April2019,next50 July2019,remaining October2019; newstock entrants physical.','Historical mandate verified; exact present delivery deadlines require current NCL/broker chain.',['SEBI/HO/MRD/DOPI/CIR/P/2018/67'])
rule('RULE-IN-02','NSE VEDL April2026 accelerated contracts','India','physical settlement example','2026-04-30','date','https://nsearchives.nseindia.com/content/circulars/CMPT73864.pdf','NCL/CMPT/73864','2026-04-23','2026-04-29','historical_verified','Corporate-action accelerated April29 expiry physically settled April30; current-specific counterexample to blanketcash overview.','Specific instrument/date only; not general deadline.',['NCL/CMPT/67750','NCL/CMPT/38039','NCL/CMPT/55330'],'2026-04-30')
rule('RULE-IN-03','NSE indices and stock derivatives covered in notice','India','expiry transition','Tuesday','weekday','https://nsearchives.nseindia.com/web/sites/default/files/inline-files/FAOP68747.pdf','NSE/FAOP/68747','2025-06-25','2025-06-26','historical_verified','Existing <=Aug31 unchanged except longdatedadjustment; newly generated >=Sep1expiry Tuesday; longdatedrealign July31EOD.','Need contractmaster, holidayadjustment andlatercircular search for specific currentseries.',['NSE/FAOP/68685'])
for id,sym,old,new in [('04','NIFTY',75,65),('05','BANKNIFTY',35,30),('06','FINNIFTY',65,60),('07','MIDCPNIFTY',140,120),('08','NIFTYNXT50',25,25)]:
 rule('RULE-IN-'+id,sym,'India','market lot transition',new,'index units/contract','https://nsearchives.nseindia.com/content/circulars/FAOP70616.pdf','NSE/FAOP/70616','2025-10-03','2025-10-28','historical_verified',f'Old lot{old}; new generation after Oct28EOD; old weekly/monthly through Dec30; longdatedconversion Dec30EOD.','This notice establishes transition, not a September2026 master-file certificate.',['SEBI/HO/MRD/TPD-1/P/CIR/2024/00181'])
rule('RULE-IN-09','BSE SENSEX weekly; SENSEX/BANKEX/SENSEX50 monthly; stock monthly','India','expiry transition','Thursday / last Thursday as product-specific','weekday','https://www.bseindia.com/markets/MarketInfo/DispNewNoticesCirculars.aspx?page=20250623-59','BSE20250623-59','2025-06-23','2025-09-01','historical_verified','SENSEX weekly Thursday; listedindexmonthly andstockmonthly lastThursday. Existing<=Aug31 unchanged; masters updated on stated differing dates.','Lateramendments/currentlots not certified. SENSEXweeklyfutures cease afterAug12; optionscontinue.',['BSE20250617-11','BSE20241128-70','BSE20240430-50'])
rule('RULE-IN-10','Indian equity option sale / exercise','India','STT observed official guidance',{'sale_rate':.15,'exercise_rate':.15},'percent','https://www.nseindia.com/static/products-services/equity-derivatives-securities-transaction-tax','NSE webpage citing FinanceAct2026','2026-04-01','2026-04-01','quarantined_current_rule','Table: sale seller onpremium; exercise purchaser onintrinsic; previous .10/.125 respectively.','Primary FinanceActchain not read; page later says settlementprice inconsistently. Do not publish as currenttax calculator.')
rule('RULE-IN-11','NSE F&O and CAS eligible cash securities','India','closing-auction transition',None,'time','https://www.nseindia.com/static/products-services/closing-auction-session','NSE/CMTR/74466; NSE/FAOP/74467','2026-05-29',None,'quarantined_current_rule','Officialpage identifies CAS timings and F&O close15:40; cashCASphase1 only F&O stocks.','Operativenotice retrieval404; commencement/amendmentchain notverified. No fixedtime adopted.')
rule('RULE-IN-12','NIFTY India FPI150 and all current listings','India','contract availability',None,'contract list','https://www.nseindia.com/static/products-services/equity-derivatives-contract-specifications','NSE specifications page','2026-08-11',None,'quarantined_current_rule','New FPI150 name appears beyond original fiveindexscope; verify introduction/masterbeforeassigning currentavailability.','Currentmaster, weekly/monthlychain, restrictions,positionlimits,marginoffsets andfreezequantities stillrequire series-specific check.')
rule('RULE-IN-13','NSE clearing overview all equity derivatives','India','settlement conflict','blanket cash wording rejected','text','https://www.nseclearing.in/clearing-settlement/equity-derivatives/settlement-mechanism','overview updated2023-09-27','2023-09-27',None,'rejected_conflicting_summary','Retain as conflict evidence; do not use its broad cash exercise sentence for individualstocks.','Specific SEBIphysical mandate and NCL2026deliverynotice outrank genericoverview.')
rule('RULE-US-01','OCC-issued standardized options','US','exercise and assignment','style/product/broker specific','procedure','https://www.theocc.com/getmedia/a151a9ae-d784-4a15-bdeb-23a029f50b70/riskstoc.pdf','ODD June2024','2024-06',None,'reviewed_principle','ChII/VIII/X differentiateexercise, settlement andbrokerinstructions; no one universalmultiplier orcutoff.','Checkcurrentsupplements andexactproduct/brokerdeadline before operationaluse.')
rule('RULE-US-02','US portfolio-margin accounts','US','margin eligibility',None,'account-specific','https://www.finra.org/rules-guidance/rulebooks/finra-rules/4210','FINRA4210(g)',None,None,'quarantined_current_rule','Teach strategybased versusportfoliomargin andbrokeroverlays.','Fullamendment/effectivedatechain notread; no accountthresholdcertified.')
rule('RULE-US-03','CME products migrated to SPAN2','US','clearing margin methodology','market risk plus liquidity and concentration components','model','https://www.cmegroup.com/clearing/risk-management/span-overview/span-2-methodology.html','CME SPAN2 overview',None,None,'reviewed_principle','Rolloutandproductcoverage separate fromframework; NSE SPAN notassumedSPAN2.','No operational parameters or marginamountcertified.')
rule('RULE-GLOBAL-01','EU/UK OTC and Eurex products','EU/UK','collateral/reporting comparison',None,'product/legal entity','https://www.esma.europa.eu/publications-and-data/interactive-single-rulebook/emir/article-41-margin-requirements-0','EMIRArt41; UKEMIR; EurexPrisma',None,None,'quarantined_current_rule','Scope comparison only; R43/R46/R69 retained.','Exactclearingthresholds, eligibility andeffectiveamendments outsidepublication.')
initial=read('research/evidence/source-checks-2026-09-21.json')['records']
algo=next(x for x in initial if x['id']=='Q025')
rule('RULE-IN-14','Retail broker/exchange algorithmic API access','India','access and restrictions',None,'account and strategy specific',algo['url'],'SEBI retail-algorithmic framework and extension chain; Q025/Q026',None,None,'quarantined_current_rule','Educational API topics do not authorize trading, deployment or redistribution.','Original framework/extension observations preserved; subsequent implementation circulars and broker permissions not certified.')
rule('RULE-IN-15','NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/NIFTYNXT50/FPI150','India','weekly/monthly availability',None,'listed series','https://www.nseindia.com/static/products-services/equity-derivatives-contract-specifications','NSE specification directory; current master required',None,None,'quarantined_current_rule','Observed page separates NIFTY weekly from other monthly listings; quarterly/longdated details are product specific.','Current daily master and introduction/discontinuation chain not reconciled; no universal weekly availability adopted.')
rule('RULE-IN-16','NSE index and stock F&O accounts','India','SPAN, delivery margin and offsets',None,'currency and percent','https://www.nseindia.com/static/products-services/equity-derivatives-contract-information','Product/capital/expiry-specific clearing circular chain not certified',None,None,'quarantined_current_rule','Teach scenario margin versus loss, collateral haircuts, expiry/delivery margin and broker add-ons.','Current risk parameter files, offset rules and implementation dates must be obtained for the exercise date.')
rule('RULE-IN-17','BSE SENSEX/BANKEX/SENSEX50 and stock derivatives','India','current lot, availability and settlement procedures',None,'contract units and dates','https://www.bseindia.com/markets/MarketInfo/DispNewNoticesCirculars.aspx?page=20250623-59','BSE current master/amendments pending;20250623-59 only proves historical transition',None,None,'quarantined_current_rule','Record index/stock and product-specific fields separately.','No current BSE lot or exact clearing deadline certified; original R60 file format is insufficient.')
for n,charge in enumerate(['brokerage','exchange and clearing fees','GST on applicable services','stamp duty','other applicable regulatory levies'],1):
 rule('RULE-IN-FEE-'+str(n),'India exchange-traded derivatives','India',charge,None,'applicable charge basis','https://www.nseindia.com/static/products-services/equity-derivatives-contract-information','Current primary schedule/statute and broker tariff required',None,None,'quarantined_current_rule','Separate this charge from STT; identify payer, calculation base, rounding and effective dates.','No rate or universal taxable base adopted; publication blocked until primary schedule and applicable account/product verified.')
rule('RULE-IN-18','India exchange-traded index/stock derivatives','India','position limits, quantity freezes and restrictions',None,'contracts, notional or percent as applicable','https://www.nseindia.com/static/products-services/equity-derivatives-contract-information','Current exchange/SEBI limit and restriction notices required',None,None,'quarantined_current_rule','Limits, surveillance restrictions and eligibility need product/account-specific worksheets.','No current threshold adopted; contract directory is a discovery source, not completed notice-chain review.')
out('market_rules',rules)
# Exact topic assignments for bounded reviewed claims supplement module reading candidates.
a=read('data/v1/associations.json')['records']
for n,rid,tids,scope,claim in [('01','RX01',['M22.01'],'Full exercising article; holder/member/broker layers','CL01'),('02','RX02',['M28.01'],'Parity assumptions and synthetic replication','CL02'),('03','R35',['M37.P01'],'Sections2–3: European totalvariance anddensity conditions, not Americanquoteprocessing','CL05'),('04','RX04',['M37.P01'],'Benchmarkscope andconclusion; dividendsnotstudied','CL06'),('05','R56',['M66.P01'],'Table5 pp17–19 versus prose; quarantine numericalheadlines','CL10'),('06','RX15',['M57.01'],'Commonpitfalls12.2 leakage','CL12')]:
 a.append({'id':'A-EXACT-'+n,'resource_id':rid,'competency_id':'C-'+tids[0].split('.')[0],'topic_ids':tids,'reading_scope':scope,'purpose':'Bounded evidence/teaching assignment; not inheritance.','status':'selected_reading','evidence_claim_ids':[claim]})
out('associations',a)
# Item-level supplemental mappings, beyond preserved complete prose blocks.
m=read('data/v1/source_mappings.json')['records']
for kind,rows in [('capstone',caps),('decision_card',cards),('specialization',branches)]:
 for x in rows:m.append({'id':'MAP-'+x['id'],'original_id':x['id'],'kind':kind,'provenance':{'source':x['source'],'line':x['line']},'canonical_ids':[x['id']],'disposition':'retained','note':'Original item individually addressable; complete surrounding policy also archived.'})
out('source_mappings',m)
print('Supplement:',len(ps),'projects',len(caps),'capstones',len(cards),'cards',len(rules),'rules')
