#!/usr/bin/env python3
"""Generate closed P13 response records from the normative API contract."""

import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schemas = json.loads((root / "docs/engineering/openapi/openapi.json").read_text())[
    "components"
]["schemas"]
names = [
    "Session",
    "Profile",
    "Credential",
    "Credentials",
    "Acknowledgment",
    "RegistrationOptions",
    "AssertionOptions",
    "CredentialDescriptor",
]
records = {}


def typ(schema, name):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return typ(next(x for x in schema["anyOf"] if x.get("type") != "null"), name)
    if schema.get("type") == "array":
        return "List<" + typ(schema["items"], name + "Item") + ">"
    if schema.get("type") == "object":
        record(name, schema)
        return name
    if isinstance(schema.get("const"), int) and not isinstance(
        schema.get("const"), bool
    ):
        return "Integer"
    if isinstance(schema.get("const"), bool):
        return "Boolean"
    return {"integer": "Integer", "boolean": "Boolean", "string": "String"}.get(
        schema.get("type"), "String"
    )


def record(name, schema):
    fields = []
    for key, value in schema["properties"].items():
        fields.append(
            "@Schema(requiredMode=Schema.RequiredMode.REQUIRED) "
            + typ(value, name + key[0].upper() + key[1:])
            + " "
            + key
        )
    records[name] = (
        "@Schema(additionalProperties=Schema.AdditionalPropertiesValue.FALSE) public record "
        + name
        + "("
        + ", ".join(fields)
        + ") {}"
    )


for name in names:
    record(name, schemas[name])
text = (
    "package org.options.platform.identity.api;\nimport java.util.List;\nimport io.swagger.v3.oas.annotations.media.Schema;\n/** Generated by scripts/generate-identity-dtos.py. */\npublic final class IdentityResponses {\n"
    + "\n".join(records.values())
    + "\n}\n"
)
(
    root
    / "backend/src/main/java/org/options/platform/identity/api/IdentityResponses.java"
).write_text(text)
