/* P06 prototype checks only. No backend/auth/API or WCAG conformance claim. */
const fs=require('fs');const path=require('path');
const toolRoot=process.env.P06_NODE_MODULES||'/tmp/p06-design-tools/node_modules';
const {chromium}=require(path.join(toolRoot,'playwright'));
const axePath=path.join(toolRoot,'axe-core/axe.min.js');
const root=path.resolve(__dirname,'..');const out=path.join(root,'design/evidence');
const routes=['home','learn','curriculum','module/M01','topic/M01.01','lesson/M01.01','resources','resource/R01','paths','path/PATH-BEGINNER','projects','project/PR01','capstone/C01','search?q=M21.01','auth/register','auth/verify','auth/login','auth/forgot','auth/reset','auth/mfa','auth/reauth','dashboard','bookmarks','notes','account','quiz','feedback','dossier','admin','editor','publish','maintenance','report/R01','methodology','review','module/M39','topic/M17.19','resource/R22'];
(async()=>{const browser=await chromium.launch({executablePath:process.env.P06_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage();let errors=[],failures=[],screenshots=[],checks=0,axeChecks=0,states=0;
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
async function go(route,width=1440,theme='light'){await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:8766/#/'+route);await page.selectOption('#appearance',theme);await page.selectOption('#scenario','ready');await page.waitForFunction(expected=>location.hash==='#/'+expected&&document.querySelector('h1')?.textContent,route);await page.waitForTimeout(30);}
for(const theme of ['light','dark'])for(const width of [320,390,768,1280,1440])for(const route of routes){await go(route,width,theme);const r=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelectorAll('h1').length,main:document.querySelectorAll('main').length,badControls:[...document.querySelectorAll('button,input,select,textarea')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().right>innerWidth+1).map(e=>e.id||e.textContent)}));checks++;if(r.overflow||r.h1!==1||r.main!==1||r.badControls.length)failures.push({route,width,theme,layout:r});
if([390,1440].includes(width)&&['home','lesson/M01.01','resources','notes','quiz','dossier','publish','curriculum','auth/register'].includes(route)){await page.addScriptTag({path:axePath});const a=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));axeChecks++;for(const v of a.violations)failures.push({route,width,theme,axe:v.id,nodes:v.nodes.map(x=>({target:x.target,summary:x.failureSummary}))});}
if((theme==='light'&&width===1440&&['home','resources','publish','curriculum','dossier'].includes(route))||(width===390&&theme==='light'&&['lesson/M01.01','resources','auth/register'].includes(route))||(theme==='dark'&&width===1440&&['lesson/M01.01','dashboard'].includes(route))){const name=route.replaceAll('/','-')+'-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,name),fullPage:true});screenshots.push(name);}}
for(const route of ['lesson/M01.01','notes','quiz','publish'])for(const state of ['loading','empty','error','offline','expired','conflict','withdrawn','exhausted']){await go(route,320);await page.selectOption('#scenario',state);states++;if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))failures.push({route,state,overflow:true});}
const interactions=[];function ok(name,condition){interactions.push({name,passed:condition});if(!condition)failures.push({interaction:name});}
await go('home',390);await page.click('#menu-toggle');ok('mobile-menu-expands',await page.getAttribute('#menu-toggle','aria-expanded')==='true');await page.getByRole('navigation',{name:'Primary',exact:true}).getByRole('link',{name:'Curriculum',exact:true}).click();await page.waitForFunction(()=>document.activeElement.tagName==='H1');ok('navigation-focuses-title',await page.evaluate(()=>document.activeElement.tagName==='H1'));
await go('lesson/M01.01',390);await page.fill('#practice-answer','abc');await page.locator('#practice-form button[type=submit]').click();ok('numeric-error-focus',await page.evaluate(()=>document.activeElement.id==='practice-answer'&&document.activeElement.getAttribute('aria-invalid')==='true'));await page.fill('#practice-answer','-150');await page.locator('#practice-form button[type=submit]').click();ok('practice-feedback',await page.locator('#feedback').textContent().then(x=>x.includes('agree')));await page.click('[data-action=bookmark]');await page.goto('http://127.0.0.1:8766/#/bookmarks');ok('bookmark-across-navigation',await page.locator('#bookmark-list').textContent().then(x=>x.includes('Units and signs')));
await go('notes',390);await page.fill('#note-text','Keep the signed units explicit.');await page.locator('#note-form button[type=submit]').click();ok('note-confirmation',await page.locator('#note-status').textContent().then(x=>x.includes('preview only')));await page.click('[data-action=conflict]');ok('dialog-focus',await page.evaluate(()=>document.activeElement.id==='dialog-title'));for(let i=0;i<12;i++)await page.keyboard.press('Tab');ok('dialog-focus-trapped',await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));await page.keyboard.press('Escape');ok('dialog-returns-focus',await page.evaluate(()=>document.activeElement.dataset.action==='conflict'));
await go('auth/register',390);await page.locator('#auth-form button[type=submit]').click();ok('auth-error-label-focus',await page.evaluate(()=>document.activeElement.id==='email'&&document.querySelector('#email').getAttribute('aria-describedby')==='email-error'));
await go('resources',390);await page.selectOption('#filter-cost','free');await page.locator('#resource-filters button[type=submit]').first().click();await page.waitForFunction(()=>location.hash.includes('cost=free')&&[...document.querySelectorAll('.resource .metadata')].every(e=>e.textContent.includes('Free')));ok('filters-shareable',page.url().includes('cost=free'));ok('resource-free-only',await page.locator('.resource .metadata').allTextContents().then(xs=>xs.every(x=>x.includes('Free'))));
await go('search?q=M21.01',390);ok('exact-id-result',await page.locator('.list-row').first().textContent().then(x=>x.includes('M21.01')));await page.check('input[name=ready]');await page.locator('#search-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('main').textContent.includes('No matching published instruction'));ok('zero-reviewed-lessons-empty',await page.locator('main').textContent().then(x=>x.includes('No matching published instruction')));
await go('dossier',320);ok('mobile-chart-data-table-open',await page.getAttribute('[data-chart-table]','open')!==null);
await go('quiz',390);await page.check('input[value=a]');await page.locator('#quiz-form button[type=submit]').click();ok('submit-confirmation',await page.locator('dialog').isVisible());await page.click('[data-action=confirm-submit]');ok('feedback-after-submit',page.url().endsWith('#/feedback'));
await go('home',320);await page.emulateMedia({reducedMotion:'reduce'});ok('reduced-motion-preference',await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));await page.addStyleTag({content:'*{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}p{margin-bottom:2em!important}'});ok('text-spacing-no-horizontal-overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await page.reload();await go('home',1280);await page.evaluate(()=>document.documentElement.style.fontSize='200%');ok('text-200-percent-no-overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
const artifactHashes=Object.fromEntries(['design/prototype/index.html','design/prototype/styles.css','design/prototype/tokens.css','design/prototype/app.js','design/prototype/content.js','scripts/verify_design_browser.cjs'].map(p=>[p,require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')]));
const result={artifactHashes,date:'2026-09-23',scope:'Local P06 design prototype only',browser:await browser.version(),viewports:[320,390,768,1280,1440],themes:['light','dark'],layoutChecks:checks,axeChecks,stateChecks:states,interactions,screenshots,runtimeErrors:[...new Set(errors)],failures,passed:!failures.length&&!errors.length,productionTestsRun:false,screenReaderTestsRun:false};fs.writeFileSync(path.join(out,'browser-validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,interactions:interactions.length,screenshots:screenshots.length},null,2));await browser.close();process.exitCode=result.passed?0:1;})();
